export const Menus = [
    { id: "menu1", name: "Menu 1" },
    { id: "menu2", name: "Menu 2" },
    { id: "menu3", name: "Menu 3" },
    { id: "menu4", name: "Menu 4" },
    { id: "menu5", name: "Menu 5" },
    { id: "menu6", name: "Menu 6" },
    { id: "menu7", name: "Menu 7" },
]

export const transactions = [
    { place: "캐시백", type: "plus", won: 2000, description: "상세 내역 1" },
    { place: "쇼핑", type: "minus", won: 13000, description: "상세 내역 1" },
    { place: "지하철", type: "minus", won: 1200, description: "상세 내역 1" },
    { place: "계좌입금", type: "plus", won: 6000, description: "상세 내역 1" },
    { place: "보험", type: "minus", won: 47000, description: "상세 내역 1" },
    { place: "캐시백", type: "plus", won: 2000, description: "상세 내역 1" },
    { place: "쇼핑", type: "minus", won: 13000, description: "상세 내역 1" },
    { place: "지하철", type: "minus", won: 1200, description: "상세 내역 1" },
    { place: "계좌입금", type: "plus", won: 6000, description: "상세 내역 1" },
    { place: "보험", type: "minus", won: 47000, description: "상세 내역 1" },
    { place: "캐시백", type: "plus", won: 2000, description: "상세 내역 1" },
    { place: "쇼핑", type: "minus", won: 13000, description: "상세 내역 1" },
    { place: "지하철", type: "minus", won: 1200, description: "상세 내역 1" },
    { place: "계좌입금", type: "plus", won: 6000, description: "상세 내역 1" },
    { place: "보험", type: "minus", won: 47000, description: "상세 내역 1" },
    { place: "캐시백", type: "plus", won: 2000, description: "상세 내역 1" },
    { place: "쇼핑", type: "minus", won: 13000, description: "상세 내역 1" },
    { place: "지하철", type: "minus", won: 1200, description: "상세 내역 1" },
    { place: "계좌입금", type: "plus", won: 6000, description: "상세 내역 1" },
    { place: "보험", type: "minus", won: 47000, description: "상세 내역 1" },
    { place: "캐시백", type: "plus", won: 2000, description: "상세 내역 1" },
    { place: "쇼핑", type: "minus", won: 13000, description: "상세 내역 1" },
    { place: "지하철", type: "minus", won: 1200, description: "상세 내역 1" },
    { place: "계좌입금", type: "plus", won: 6000, description: "상세 내역 1" },
    { place: "보험", type: "minus", won: 47000, description: "상세 내역 1" },
]
